# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: textlint

on:
  push:

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: node
        name: Check node version
        run: |
          echo ::set-output name=version::$(cat .node-version)
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node.outputs.version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Textlint
        run: yarn lint
